x-build: &x-build
  context: .
  dockerfile: Dockerfile

x-common: &x-common
  image: cxxmpi-dev:latest
  init: true
  environment:
    MPI_HOSTS: h1,h2,h3,h4
  volumes:
    - ..:/workspaces/cxxmpi:cached
  cap_add:
    - SYS_PTRACE
  security_opt:
    - seccomp:unconfined
  privileged: true
  command: >
    bash -c "sudo service ssh restart && sleep infinity"

services:
  h1:
    <<: *x-common
    hostname: h1
    container_name: cxxmpi-dev-h1
    build: *x-build

  h2:
    <<: *x-common
    hostname: h2
    container_name: cxxmpi-dev-h2

  h3:
    <<: *x-common
    hostname: h3
    container_name: cxxmpi-dev-h3

  h4:
    <<: *x-common
    hostname: h4
    container_name: cxxmpi-dev-h4
